application: sanktex-hrd
version: dev
runtime: python
api_version: 1

builtins:
- admin_redirect: on
- datastore_admin: on
- appstats: on
- remote_api: on

handlers:
- url: /static
  static_dir: static

#- url: /favicon.ico
#  static_files: static/favicon.png
#  upload: static/favicon.png

- url: /media/
  static_dir: media

- url: /_ah/queue/deferred
  script: $PYTHON_LIB/google/appengine/ext/deferred/handler.py
  login: admin

- url: /mapreduce(/.*)?
  script: mapreduce/main.py
  login: admin
  
- url: /_ah/login_required
  script: lib/gaetk/gaetk/login.py

- url: /logout
  script: lib/gaetk/gaetk/login.py

- url: /.*
  script: sanctions/views.py

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?index\.yaml
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?\..*
- ^(.*/)?CHANGES
- ^(.*/)?LICENSE
- ^(.*/)?Makefile
- ^(.*/)?requirements\.txt
- ^(.*/)?setup.py
- ^(.*/)?docs?/.*
- ^(.*/)?README.*
- ^(.*/)?lib/google_appengine/.*
