application: sanktex-hrd
version: dev
runtime: python27
api_version: 1
threadsafe: yes
instance_class: F1


builtins:
- admin_redirect: on
- remote_api: off
- appstats: on
- deferred: on
# See also https://github.com/freshplanet/AppEngine-Deferred
# for an alternative

handlers:
- url: /static
  static_dir: static

#- url: /favicon.ico
#  static_files: static/favicon.png
#  upload: static/favicon.png

- url: /media/
  static_dir: media

- url: (/_ah/login_required|/gaetk/auth/.*)
  script: login.application

- url: /mapreduce(/.*)?
  script: mapreduce.main.APP
  login: admin

- url: /(version.txt|robots.txt|_ah/warmup)
  script: gaetk.defaulthandlers.application

- url: /.*
  script: sanctions.views.application

libraries:
- name: jinja2
  version: "2.6"
- name: setuptools
  version: "0.6c11"
- name: markupsafe
  version: "0.15"
- name: webapp2
  version: latest
- name: ssl
  version: latest
- name: numpy
  version: latest
- name: PIL
  version: latest

skip_files:
- ^(.*/)?app\.yaml
- ^(.*/)?index\.yaml
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?\..*
- ^(.*/)?(CHANGES|LICENSE|AUTHORS)
- ^(.*/)?Makefile
- ^(.*/)?requirements\.txt
- ^(.*/)?setup.py
- ^.*/(doc|example|test|bin)s?/.*
- ^(doc|example|test|bin)s?/.*
- ^.+/README.*
- ^(.*/)?lib/.*/(cups-backends|odbc_bridge|softm_express|tests|testsuite)/.*
- ^(.*/)?lib/CentralServices/keys/.*
- ^(.*/)?lib/jinja2/(scripts|custom_fixers_artwork)/.*
- ^(.*/)?lib/.*google_appengine/.*
- ^(.*/)?lib/gae-sessions/(demo|demo-with-google-logins|docs|tests)/.*
- ^(.*/)?lib/fmtp/printclient/.*
- ^(.*/)?testenv/.*
- ^(.*/)?pythonenv/.*
- ^(.*/)?(CHANGES|LICENSE|AUTHORS)
- transferfromsoftm/.*
- .*\.jar
- ^(.*/)?node_modules/.*
- ^js_src/.*
- ^tmp/.*
- ^venv/.*